service_lines:
  - key: emergency_medicine
    display_name: "Emergency Medicine"
    capacity_label: "Visits"
    default:
      total_units: 30
      occupancy_pct: 75
      unit_rev: 1200
      unit_cost: 800
      referrals_per_unit: 1.3
    referrals:
      revenue_per_referral: 900
      types:
        - name: "Imaging"
          pct: 25
        - name: "Lab"
          pct: 25
        - name: "OBS/IP admissions"
          pct: 25
        - name: "Specialty consults"
          pct: 25
    locum:
      enabled: true
      default_count: 1
      utilization_pct: 80
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390
    assumptions:
      - "Per-visit revenue/cost are placeholders; replace with site-specific values."
      - "Downstream lever mix equal-split; adjust to your patterns."

  - key: hospital_medicine_inpatient
    display_name: "Hospital Medicine (Inpatient)"
    capacity_label: "Beds"
    default:
      total_units: 22
      occupancy_pct: 75
      unit_rev: 2750
      unit_cost: 1850
      referrals_per_unit: 1.2
    referrals:
      revenue_per_referral: 900
      types:
        - name: "Pharmacy/Lab"
          pct: 25
        - name: "Imaging"
          pct: 25
        - name: "Specialty consults"
          pct: 25
        - name: "Post-acute (IRF/SNF/HHA)"
          pct: 25
    locum:
      enabled: true
      default_count: 1
      utilization_pct: 80
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390
    assumptions:
      - "Per-bed/day revenue & cost mirror med-surg starter values; confirm locally."

  - key: critical_care_icu
    display_name: "Critical Care (ICU)"
    capacity_label: "Beds"
    default:
      total_units: 14
      occupancy_pct: 75
      unit_rev: 8000
      unit_cost: 4500
      referrals_per_unit: 1.8
    referrals:
      revenue_per_referral: 900
      types:
        - name: "ICU days"
          pct: 20
        - name: "Dialysis"
          pct: 20
        - name: "IR lines/procedures"
          pct: 20
        - name: "High-cost drugs"
          pct: 20
        - name: "LTACH/IRF"
          pct: 20
    locum:
      enabled: true
      default_count: 1
      utilization_pct: 80
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390
    assumptions:
      - "ICU per-day revenue/cost are placeholders; adjust to payer mix/case mix."

  - key: anesthesiology_crna
    display_name: "Anesthesiology / CRNA"
    capacity_label: "Cases"
    default:
      total_units: 10
      occupancy_pct: 75
      unit_rev: 1000
      unit_cost: 600
      referrals_per_unit: 0.3
    referrals:
      revenue_per_referral: 900
      types:
        - name: "OR throughput"
          pct: 25
        - name: "Implants"
          pct: 25
        - name: "Regional blocks"
          pct: 25
        - name: "Pain procedures"
          pct: 25
    locum:
      enabled: true
      default_count: 1
      utilization_pct: 80
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390
    assumptions:
      - "Per-case anesthesia economics vary widely; treat as placeholders."

  - key: ob_gyn_ld
    display_name: "OB-GYN (L&D)"
    capacity_label: "Deliveries"
    default:
      total_units: 8
      occupancy_pct: 75
      unit_rev: 7000
      unit_cost: 3500
      referrals_per_unit: 0.8
    referrals:
      revenue_per_referral: 900
      types:
        - name: "C-sections/OR"
          pct: 25
        - name: "NICU days"
          pct: 25
        - name: "Ultrasound"
          pct: 25
        - name: "Women's health follow-up"
          pct: 25
    locum:
      enabled: true
      default_count: 1
      utilization_pct: 80
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390
    assumptions:
      - "Delivery revenue/cost vary by DRG and payer; placeholders."

  - key: neonatology_nicu
    display_name: "Neonatology / NICU"
    capacity_label: "Patient Days"
    default:
      total_units: 10
      occupancy_pct: 75
      unit_rev: 6000
      unit_cost: 3500
      referrals_per_unit: 0.6
    referrals:
      revenue_per_referral: 900
      types:
        - name: "NICU days/vent"
          pct: 25
        - name: "Imaging"
          pct: 25
        - name: "Peds subspecialty referrals"
          pct: 25
        - name: "Therapies"
          pct: 25
    locum:
      enabled: true
      default_count: 1
      utilization_pct: 80
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390
    assumptions:
      - "High acuity; defaults are illustrative only."

  - key: psychiatry_ip_op_tele
    display_name: "Psychiatry (IP/OP/Tele)"
    capacity_label: "Encounters"
    default:
      total_units: 16
      occupancy_pct: 75
      unit_rev: 1500
      unit_cost: 900
      referrals_per_unit: 0.7
    referrals:
      revenue_per_referral: 900
      types:
        - name: "Psych unit days"
          pct: 25
        - name: "IOP/PHP"
          pct: 25
        - name: "ED decompression"
          pct: 25
        - name: "Addiction services"
          pct: 25
    locum:
      enabled: true
      default_count: 1
      utilization_pct: 80
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390
    assumptions:
      - "Mix spans IP/OP/Tele; tune to program."

  - key: diagnostic_radiology_teleradiology
    display_name: "Diagnostic Radiology / Teleradiology"
    capacity_label: "Studies"
    default:
      total_units: 60
      occupancy_pct: 75
      unit_rev: 400
      unit_cost: 150
      referrals_per_unit: 0.3
    referrals:
      revenue_per_referral: 900
      types:
        - name: "Technical imaging volumes"
          pct: 34
        - name: "IR referrals"
          pct: 33
        - name: "Oncology/surgery pipeline"
          pct: 33
    locum:
      enabled: false
      default_count: 1
      utilization_pct: 80
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390
    assumptions:
      - "Reads per shift vary by modality blend; placeholders."

  - key: interventional_radiology
    display_name: "Interventional Radiology"
    capacity_label: "Procedures"
    default:
      total_units: 8
      occupancy_pct: 75
      unit_rev: 6000
      unit_cost: 3000
      referrals_per_unit: 0.9
    referrals:
      revenue_per_referral: 900
      types:
        - name: "Embolization/ablation"
          pct: 25
        - name: "Dialysis access"
          pct: 25
        - name: "Device pass-throughs"
          pct: 25
        - name: "Admissions"
          pct: 25
    locum:
      enabled: true
      default_count: 1
      utilization_pct: 80
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390

  - key: general_surgery
    display_name: "General Surgery"
    capacity_label: "Cases"
    default:
      total_units: 6
      occupancy_pct: 75
      unit_rev: 12000
      unit_cost: 8000
      referrals_per_unit: 0.7
    referrals:
      revenue_per_referral: 900
      types:
        - name: "OR time/implants"
          pct: 25
        - name: "Pathology"
          pct: 25
        - name: "Imaging"
          pct: 25
        - name: "Wound care"
          pct: 25
    locum:
      enabled: false
      default_count: 1
      utilization_pct: 80
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390

  - key: orthopedic_surgery
    display_name: "Orthopedic Surgery"
    capacity_label: "Cases"
    default:
      total_units: 6
      occupancy_pct: 75
      unit_rev: 16000
      unit_cost: 10000
      referrals_per_unit: 0.6
    referrals:
      revenue_per_referral: 900
      types:
        - name: "OR implants (joints/trauma)"
          pct: 20
        - name: "PT/OT"
          pct: 20
        - name: "Imaging"
          pct: 20
        - name: "DME"
          pct: 20
        - name: "Revisions"
          pct: 20
    locum:
      enabled: false
      default_count: 1
      utilization_pct: 80
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390

  - key: trauma_surgery_acute_care
    display_name: "Trauma Surgery (Acute Care Surgery)"
    capacity_label: "Activations"
    default:
      total_units: 8
      occupancy_pct: 75
      unit_rev: 10000
      unit_cost: 7000
      referrals_per_unit: 1.2
    referrals:
      revenue_per_referral: 900
      types:
        - name: "Trauma activations"
          pct: 20
        - name: "Emergent OR"
          pct: 16
        - name: "ICU days"
          pct: 16
        - name: "Imaging/Lab/Blood products"
          pct: 16
        - name: "Specialty consults (Ortho/Neuro/Plastics)"
          pct: 16
        - name: "Rehab"
          pct: 16
    locum:
      enabled: true
      default_count: 1
      utilization_pct: 80
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390

  - key: gastroenterology_endoscopy
    display_name: "Gastroenterology (Endoscopy)"
    capacity_label: "Cases"
    default:
      total_units: 12
      occupancy_pct: 75
      unit_rev: 3000
      unit_cost: 1500
      referrals_per_unit: 0.8
    referrals:
      revenue_per_referral: 900
      types:
        - name: "Colonoscopy/EGD/ERCP volumes"
          pct: 34
        - name: "Pathology"
          pct: 33
        - name: "Surgery/oncology referrals"
          pct: 33
    locum:
      enabled: false
      default_count: 1
      utilization_pct: 80
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390

  - key: gastroenterology_outpatient_no_eus_ercp
    display_name: "Gastroenterology (Outpatient only — no EUS/ERCP)"
    capacity_label: "Cases"
    default:
      total_units: 14
      occupancy_pct: 75
      unit_rev: 1800    # outpatient colonoscopy/EGD typical; adjust to your site
      unit_cost: 900
      referrals_per_unit: 0.5
    referrals:
      revenue_per_referral: 900
      types:
        - name: "Pathology"
          pct: 35
        - name: "GI clinic follow-up"
          pct: 25
        - name: "Imaging"
          pct: 20
        - name: "Surgery referrals"
          pct: 20
    locum:
      enabled: false
      default_count: 0
      utilization_pct: 0
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390
    assumptions:
      - "Outpatient GI only; excludes EUS/ERCP. Revenues/costs are placeholders."

  - key: cardiology_noninvasive
    display_name: "Cardiology (Non-invasive)"
    capacity_label: "Studies"
    default:
      total_units: 20
      occupancy_pct: 75
      unit_rev: 600
      unit_cost: 250
      referrals_per_unit: 0.7
    referrals:
      revenue_per_referral: 900
      types:
        - name: "Echo/stress/nuclear/CTA"
          pct: 25
        - name: "Cath-lab conversions"
          pct: 25
        - name: "HF clinic"
          pct: 25
        - name: "Cardiac rehab"
          pct: 25
    locum:
      enabled: false
      default_count: 1
      utilization_pct: 80
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390

  - key: interventional_cardiology
    display_name: "Interventional Cardiology"
    capacity_label: "Procedures"
    default:
      total_units: 8
      occupancy_pct: 75
      unit_rev: 14000
      unit_cost: 9000
      referrals_per_unit: 0.9
    referrals:
      revenue_per_referral: 900
      types:
        - name: "PCI/structural heart"
          pct: 25
        - name: "ICU/step-down"
          pct: 25
        - name: "Cardiac rehab"
          pct: 25
        - name: "Device/pharmacy"
          pct: 25
    locum:
      enabled: true
      default_count: 1
      utilization_pct: 80
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390

  - key: electrophysiology
    display_name: "Electrophysiology"
    capacity_label: "Procedures"
    default:
      total_units: 6
      occupancy_pct: 75
      unit_rev: 12000
      unit_cost: 8000
      referrals_per_unit: 0.6
    referrals:
      revenue_per_referral: 900
      types:
        - name: "Ablations/device implants"
          pct: 34
        - name: "Device-clinic monitoring"
          pct: 33
        - name: "Anticoag management"
          pct: 33
    locum:
      enabled: false
      default_count: 1
      utilization_pct: 80
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390

  - key: neurology_telestroke
    display_name: "Neurology / Telestroke"
    capacity_label: "Encounters"
    default:
      total_units: 10
      occupancy_pct: 75
      unit_rev: 2000
      unit_cost: 1200
      referrals_per_unit: 0.9
    referrals:
      revenue_per_referral: 900
      types:
        - name: "Stroke admissions"
          pct: 25
        - name: "tPA/TNK"
          pct: 25
        - name: "Thrombectomy referrals"
          pct: 25
        - name: "Rehab"
          pct: 25
    locum:
      enabled: true
      default_count: 1
      utilization_pct: 80
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390

  - key: hematology_oncology
    display_name: "Hematology/Oncology"
    capacity_label: "Encounters"
    default:
      total_units: 12
      occupancy_pct: 75
      unit_rev: 4000
      unit_cost: 2500
      referrals_per_unit: 0.8
    referrals:
      revenue_per_referral: 900
      types:
        - name: "Infusion center (chemo/biologics/340B)"
          pct: 25
        - name: "Imaging"
          pct: 25
        - name: "Radiation oncology"
          pct: 25
        - name: "Genetics"
          pct: 25
    locum:
      enabled: false
      default_count: 1
      utilization_pct: 80
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390

  - key: radiation_oncology
    display_name: "Radiation Oncology"
    capacity_label: "Fractions"
    default:
      total_units: 15
      occupancy_pct: 75
      unit_rev: 1500
      unit_cost: 700
      referrals_per_unit: 0.4
    referrals:
      revenue_per_referral: 900
      types:
        - name: "Fractions (IMRT/SBRT/SRS)"
          pct: 25
        - name: "Planning/sim"
          pct: 25
        - name: "Anesthesia (peds)"
          pct: 25
        - name: "Surgery referrals"
          pct: 25
    locum:
      enabled: false
      default_count: 1
      utilization_pct: 80
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390

  - key: nephrology
    display_name: "Nephrology"
    capacity_label: "Encounters"
    default:
      total_units: 10
      occupancy_pct: 75
      unit_rev: 800
      unit_cost: 400
      referrals_per_unit: 0.7
    referrals:
      revenue_per_referral: 900
      types:
        - name: "Acute dialysis"
          pct: 25
        - name: "Vascular access (IR/vascular)"
          pct: 25
        - name: "Transplant referrals"
          pct: 25
        - name: "ESA pharmacy"
          pct: 25
    locum:
      enabled: false
      default_count: 1
      utilization_pct: 80
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390

  - key: infectious_diseases
    display_name: "Infectious Diseases"
    capacity_label: "Encounters"
    default:
      total_units: 12
      occupancy_pct: 75
      unit_rev: 500
      unit_cost: 250
      referrals_per_unit: 0.6
    referrals:
      revenue_per_referral: 900
      types:
        - name: "OPAT/infusion"
          pct: 25
        - name: "PICC (IR)"
          pct: 25
        - name: "Imaging"
          pct: 25
        - name: "Wound care"
          pct: 25
    locum:
      enabled: false
      default_count: 1
      utilization_pct: 80
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390

  - key: urology
    display_name: "Urology"
    capacity_label: "Cases"
    default:
      total_units: 6
      occupancy_pct: 75
      unit_rev: 8000
      unit_cost: 5000
      referrals_per_unit: 0.6
    referrals:
      revenue_per_referral: 900
      types:
        - name: "OR (TURP/HoLEP/stones)"
          pct: 25
        - name: "Imaging"
          pct: 25
        - name: "Oncology (prostate/bladder)"
          pct: 25
        - name: "DME"
          pct: 25
    locum:
      enabled: false
      default_count: 1
      utilization_pct: 80
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390

  - key: pmr_inpatient_rehab
    display_name: "PM&R (Inpatient Rehab)"
    capacity_label: "Patient Days"
    default:
      total_units: 12
      occupancy_pct: 75
      unit_rev: 4500
      unit_cost: 2500
      referrals_per_unit: 0.5
    referrals:
      revenue_per_referral: 900
      types:
        - name: "IRF case revenue"
          pct: 34
        - name: "OP therapy"
          pct: 33
        - name: "DME/orthotics"
          pct: 33
    locum:
      enabled: false
      default_count: 1
      utilization_pct: 80
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390

  - key: pain_medicine
    display_name: "Pain Medicine"
    capacity_label: "Procedures"
    default:
      total_units: 10
      occupancy_pct: 75
      unit_rev: 1500
      unit_cost: 800
      referrals_per_unit: 0.6
    referrals:
      revenue_per_referral: 900
      types:
        - name: "Injections/RF/stim implants"
          pct: 25
        - name: "Imaging"
          pct: 25
        - name: "PT"
          pct: 25
        - name: "Pharmacy"
          pct: 25
    locum:
      enabled: false
      default_count: 1
      utilization_pct: 80
      hourly_rate: 265
      hours_per_shift: 10
      travel_per_day: 390
